# Generated by Django 5.2.8 on 2026-03-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='opt_out_date',
            field=models.BooleanField(default=False),
        ),
    ]
