# Generated by Django 5.2.8 on 2026-03-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_opt_out_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('investment_budget', models.CharField(max_length=255)),
                ('interested_sector', models.CharField(max_length=255)),
                ('source_platform', models.CharField(db_index=True, default='manual', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='exhibitorregistration',
            name='api_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exhibitorregistration',
            name='source_platform',
            field=models.CharField(db_index=True, default='manual', max_length=255),
        ),
        migrations.AddField(
            model_name='visitorregistration',
            name='api_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitorregistration',
            name='source_platform',
            field=models.CharField(db_index=True, default='manual', max_length=255),
        ),
    ]
