# Generated by Django 5.2.8 on 2026-03-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_investorregistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorregistration',
            name='firm_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
