# Generated by Django 5.2.8 on 2026-03-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_contactinquiry_exhibitorregistration_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorregistration',
            name='business_experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investorregistration',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
