# Generated by Django 5.2.8 on 2026-03-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_investorregistration_business_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorregistration',
            name='business_experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitorregistration',
            name='investment_budget',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
