# Generated by Django 5.2.8 on 2026-03-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_visitorregistration_business_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorregistration',
            name='companies_financed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
