# Generated by Django 5.2.8 on 2026-03-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_investorregistration_companies_financed'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitorregistration',
            name='founded_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exhibitorregistration',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exhibitorregistration',
            name='investment_required',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exhibitorregistration',
            name='units_operating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
