# Generated by Django 5.2.8 on 2026-03-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_exhibitorregistration_founded_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitorregistration',
            name='roi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
