# Generated by Django 5.2.8 on 2026-03-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitorregistration',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorregistration',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
