# Generated by Django 5.2.8 on 2026-03-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_exhibitorregistration_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorregistration',
            name='franchisor_interest',
            field=models.TextField(blank=True, null=True),
        ),
    ]
