# Generated by Django 5.2.8 on 2026-04-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_visitorregistration_franchisor_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='source_platform',
            field=models.CharField(db_index=True, default='igtf', max_length=255),
        ),
    ]
