# Generated by Django 5.2.8 on 2026-04-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_contactinquiry_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitorregistration',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exhibitorregistration',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investorregistration',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investorregistration',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
