# Generated by Django 5.2.8 on 2026-04-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitorregistration',
            name='event_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exhibitorregistration',
            name='stall_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
