# Generated by Django 5.2.8 on 2026-04-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_exhibitorregistration_event_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_stall_layout',
            field=models.BooleanField(default=False),
        ),
    ]
