# Generated by Django 5.2.8 on 2026-04-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_event_has_stall_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorregistration',
            name='event_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
