# Generated by Django 5.2.8 on 2026-04-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_visitorregistration_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorregistration',
            name='event_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investorregistration',
            name='event_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
