# Generated by Django 5.2.8 on 2026-04-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_investorregistration_event_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='pavilion_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
