# Generated by Django 5.2.8 on 2026-04-17 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_sector_pavilion_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='pavilion_id',
        ),
    ]
