# Generated by Django 5.2.8 on 2026-04-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_sector_pavilion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
