# Generated by Django 6.0.4 on 2026-04-20 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_contactinquiry_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitorregistration',
            name='about',
        ),
        migrations.RemoveField(
            model_name='exhibitorregistration',
            name='founded_year',
        ),
        migrations.RemoveField(
            model_name='exhibitorregistration',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='exhibitorregistration',
            name='investment_required',
        ),
        migrations.RemoveField(
            model_name='exhibitorregistration',
            name='roi',
        ),
        migrations.RemoveField(
            model_name='exhibitorregistration',
            name='units_operating',
        ),
        migrations.CreateModel(
            name='FranchisorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person_name', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('units_operating', models.IntegerField(blank=True, null=True)),
                ('investment_required', models.CharField(blank=True, max_length=255, null=True)),
                ('roi', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('event_location', models.CharField(blank=True, max_length=255, null=True)),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('source_platform', models.CharField(db_index=True, default='nfis', max_length=255)),
                ('api_source', models.CharField(blank=True, max_length=255, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
