# Generated by Django 6.0.4 on 2026-04-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_exhibitorregistration_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchisorregistration',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='franchisorregistration',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='franchisorregistration',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
