# Generated by Django 6.0.4 on 2026-04-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_franchisorregistration_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('sales', 'Sales'), ('franchisor', 'Franchisor'), ('investor', 'Investor'), ('executive', 'Executive')], default='sales', max_length=20),
        ),
    ]
