# Generated by Django 6.0.4 on 2026-04-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchisorregistration',
            name='break_even',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='franchisorregistration',
            name='cities',
            field=models.TextField(blank=True, help_text='Comma separated cities', null=True),
        ),
        migrations.AddField(
            model_name='franchisorregistration',
            name='franchise_fee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='franchisorregistration',
            name='location_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='franchisorregistration',
            name='marketing_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='franchisorregistration',
            name='product_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='franchisorregistration',
            name='royalty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='franchisorregistration',
            name='setup_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='franchisorregistration',
            name='space_requirement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='franchisorregistration',
            name='training_support',
            field=models.BooleanField(default=False),
        ),
    ]
