# Generated by Django 5.2.8 on 2026-04-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_franchisorregistration_break_even_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseInquiry',
            fields=[
            ],
            options={
                'verbose_name': 'Franchise Application',
                'verbose_name_plural': 'Franchise Applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.contactinquiry',),
        ),
        migrations.CreateModel(
            name='InvestorInquiry',
            fields=[
            ],
            options={
                'verbose_name': 'Investor Inquiry',
                'verbose_name_plural': 'Investor Inquiries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.contactinquiry',),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('franchise', 'Franchise Application'), ('investor', 'Investor Inquiry'), ('general', 'General Contact')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='target_name',
            field=models.CharField(blank=True, help_text='Brand or Investor name', max_length=255, null=True),
        ),
    ]
